# POC FNE : Wikibase with Query Service
#
# This docker-compose is a custom setup made for FNE proof of concept :
# https://github.com/abes-esr/poc-fne

version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.32-bundle
    links:
      - mysql
    ports:
     - "8181:80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
    depends_on:
      - mysql
      - elasticsearch
    restart: on-failure
    networks:
      default:
        aliases:
         - wikibase.svc
         # CONFIG - Add your real wikibase hostname here, for example wikibase-registry.wmflabs.org
    # CONFIG - Add your custom `env/.wb_env` based on `env/dot_wb_env` model
    env_file: env/.wb_env
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
    tty: true # Colorize logs
  mysql:
    image: mariadb:10.3
    restart: always
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    # CONFIG - Add your custom `env/.mysql_env` based on `env/dot_mysql_env` model
    env_file: env/.mysql_env
    networks:
      default:
        aliases:
         - mysql.svc
    tty: true # Colorize logs
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    ports:
     - "8282:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs-proxy.svc
    logging:
      driver: none
  wdqs:
    image: wikibase/wdqs:0.3.0
    # A 'z' or 'Z' flag is required to run on CentOS 7.6 with Docker 1.13.1
    # Without this flag, the root user fails to access /wdqs/data/data.jnl: "Permission Denied".
    # This is due to SELinux being enabled, but the exact way it prevents the container to access the file is unclear
    # See z/Z flags documentation: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
    volumes:
      - query-service-data:/wdqs/data:Z
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: wikibase/wdqs:0.3.0
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
  elasticsearch:
    image: wikibase/elasticsearch:5.6.14-extra
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    logging:
      driver: none

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
