# POC FNE : Wikibase with Query Service
#
# This docker-compose is a custom setup made for FNE proof of concept :
# https://github.com/abes-esr/poc-fne
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.32-bundle
    build:
      context: ./wikibase/1.32/bundle
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
     - "8181:80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
    depends_on:
    - mysql
    - elasticsearch
    networks:
      default:
        aliases:
         - wikibase.svc
    # CONFIG - Add your custom `env/.wb_env` based on `env/dot_wb_env` model
    env_file: env/.wb_env
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
  mysql:
    image: mariadb:latest
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    env_file: env/.mysql_env
    networks:
      default:
        aliases:
         - mysql.svc
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    build:
      context: ./wdqs-frontend/latest
      dockerfile: Dockerfile
    ports:
     - "8282:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs-proxy.svc
  wdqs:
    image: wikibase/wdqs:0.3.0
    restart: always
    build:
      context: ./wdqs/0.3.0
      dockerfile: Dockerfile
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    build:
      context: ./wdqs-proxy/latest
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: wikibase/wdqs:0.3.0
    build:
      context: ./wdqs/0.3.0
      dockerfile: Dockerfile
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
  elasticsearch:
    image: wikibase/elasticsearch:5.6.14-extra
    build:
      context: ./elasticsearch/5.6.14-extra
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
