# POC FNE : Wikibase with Query Service
#
# This docker-compose is a custom setup made for FNE proof of concept :
# https://github.com/abes-esr/poc-fne

version: '3'

services:
  wikibase:
    build:
      context: ./wikibase/1.33/bundle
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
     - "8181:80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
    depends_on:
      - mysql
      - elasticsearch
    restart: on-failure
    networks:
      default:
        aliases:
         - wikibase.svc
         # CONFIG - Add your real wikibase hostname here, for example wikibase-registry.wmflabs.org
         # Commenting out alias as the wdqs-updater was encountering connection errors, apparently because of it:
         # java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to poc-fne.abes.fr:443 [poc-fne.abes.fr/172.30.0.6] failed: Connection refused (Connection refused)
         # - poc-fne.abes.fr
    # CONFIG - Add your custom `env/.wb_env` based on `env/dot_wb_env` model
    env_file: env/.wb_env
    environment:
      - DB_SERVER=mysql.svc:3306
      - MW_ELASTIC_HOST=elasticsearch.svc
      - MW_ELASTIC_PORT=9200
    tty: true # Colorize logs
  mysql:
    image: mariadb:10.3
    restart: on-failure
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    # CONFIG - Add your custom `env/.mysql_env` based on `env/dot_mysql_env` model
    env_file: env/.mysql_env
    networks:
      default:
        aliases:
         - mysql.svc
    tty: true # Colorize logs
  wdqs-frontend:
    build:
      context: ./wdqs-frontend/latest
      dockerfile: Dockerfile
    restart: on-failure
    ports:
     - "8282:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    env_file: env/.wdqs
    environment:
      - WDQS_HOST=wdqs-proxy.svc
    logging:
      driver: none
  wdqs:
    image: wikibase/wdqs:0.3.2
    restart: on-failure
    # Required to run on CentOS 7.6 with Docker 1.13.1
    # Without this flag, the root user fails to access /wdqs/data/data.jnl: "Permission Denied"
    # Clues on why we get this message:
    # - SELinux is enabled and might be messing with this container's file permissions
    # - there are known issues with mounting BlazeGraph data file: https://github.com/lyrasis/docker-blazegraph/issues/12
    privileged: true
    # 'z' flag required to run on CentOS 7.6 with Docker 1.13.1
    # Without this flag, the root user fails to access /wdqs/data/data.jnl: "Permission Denied".
    # This is due to SELinux being enabled, but the exact way it prevents the container to access the file is unclear
    # See z/Z flags documentation: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
    volumes:
      - query-service-data:/wdqs/data:Z
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    env_file: env/.wdqs
    environment:
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    ports:
      - "9999:9999"
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: on-failure
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
  wdqs-updater:
    image: wikibase/wdqs:0.3.2
    restart: on-failure
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    env_file: env/.wdqs
    environment:
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
  elasticsearch:
    image: wikibase/elasticsearch:5.6.14-extra
    restart: on-failure
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    logging:
      driver: none

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
